### ISSUE TITLE
Bug when conveyor gets overflown

### ISSUE THREAD

**Issue by imsys** [RhinoRhys/LinearLogistics#1]
I just updated the mod to the latest version (v0.1.0), the balancer from the older version disappeared, so I placed them all again. (not a big problem, I had them just on some places)

The new version works nicer, as it balances correctly and it's now stackable, but it introduced some bugs.

One that I show in this video:
https://youtu.be/0rSwVTFxp7s

when just one of the output conveyers get overflown, the balancer simply stops.

Another thing that happened is if I save the game and reopen it, then some balancers just stops working, and I have to remove them and place them again and do all the connections again to work.

Anyway, I also want to say thanks a lot for this mod! I can't think of managing some complex balancing without it anymore.

**Comment by RhinoRhys** [comment]
thank you for letting me know, I have updated the mod to fix this issue :)
