### ISSUE TITLE
One specific balancer stops working after reloading game

### ISSUE THREAD

**Issue by imsys** [RhinoRhys/LinearLogistics#2]
Thanks, the overflow issue was fixed, there is just another issue that I do not understand the pattern to replicate it.

After reloading the game, there is a specific balancer that stops working, I have to remove it, create it again and reconnect to work.

https://youtu.be/QHRR9VTFdUY

**Comment by imsys** [comment]
I'm doing some debugging here.
I connected one conveyor, saved, reloaded, connected another one, saved and reloaded. By doing this, everything was working and the bug did not occur.

So then I disconnected every conveyor, and connected everything at once and saved. Then the bug occurred. I will do some more testing to understand the pattern.

**Comment by imsys** [comment]
while doing the test, by saving and reloading. Then another 7x balancer stopped working.

**Comment by mindforger** [comment]
well ... for me (using 0.1.1) the balancers don't work at all ... palced a couple and they dont do anything besides connecting to the belts

**Comment by RhinoRhys** [comment]
hopefully the latest version should fix your issues :)

**Comment by mindforger** [comment]
can confirm after update to 0.2.0 seem to work, no hanging until now for 2 reloads

**Comment by mindforger** [comment]
sorry it stoppped again after the third continuation of the world, it looks like it lost the connection to the belts

usually you can place stuf against a belt and it connects, but the balancers don't seem to, maybe the issue is there?

**Comment by imsys** [comment]
> 
> 
> sorry it stoppped again after the third continuation of the world, it looks like it lost the connection to the belts
> 
> usually you can place stuf against a belt and it connects, but the balancers don't seem to, maybe the issue is there?

v0.2.1 fixed for me, @mindforger , did you tried it? you will have to delete the old balancer and add it again, and connect the belts again, but it should work now.

**Comment by mindforger** [comment]
i did not had 0.2.1 i just had 0.2.0 at the point of my post close comment, will try with 0.2.1 ... had removed all balancers in the mean time, will prepare a loopdidoop test setup before using it again and see for several reloads how it behaves

**Comment by simon-horny** [comment]
Hey, love your mode mate, saves a fuckton of time. Anyways, I'm using 0.2.1 and I'm still getting the same bug, my balancers get stuck, it's not as the guy before said that they lose connection, but I have to completely remove them an replace them for it to work. 
Anyways, I suggest reopening the issue.

**Comment by mindforger** [comment]
@simon-horny was that balancer present BEFORE the patch? @imsys stated you might have to replace and reconnect them ALL after patching ... my test rig with 3 balancers and a big loop of items is still working fine after 7 reloads

**Comment by simon-horny** [comment]
Ffs, you're right, I'll test it properly then.
