### ISSUE TITLE
Is this going to get updated for update 5

### ISSUE THREAD

**Issue by MarkJepson** [RhinoRhys/LinearLogistics#7]
Just wondering if this is going to get updated for update 5? If not if someone can be found are you willing to let someone take over the dev?

**Comment by mklierman** [comment]
I'd be willing to take it over if RhinoRhys is no longer interested

**Comment by Death-Strike-Gaming** [comment]
> I'd be willing to take it over if RhinoRhys is no longer interested. I have a bit of modding experience: https://ficsit.app/user/4Mpda7UPxKixEB

Looks like it hasnt been updated and we are on update 6, a 1 input and 2 output splitter and 2 input 1 output merger would also be nice for when you only need a two lane 50/50 and not a 3 way.

**Comment by RhinoRhys** [comment]
Sorry I stopped playing so won't be updating. There is already a great replacement mod called "modular load balancer"
