### ISSUE TITLE
No longer balancing

### ISSUE THREAD

**Issue by mikeloeven** [RhinoRhys/LinearLogistics#8]
As of U7 the splitters are no longer balancing outputs one output seems to take priority and it will not split the input unless the first output is saturated expected behavior is to properly split evenly among the outputs. they are not really usable in their current state

**Comment by RhinoRhys** [comment]
Sorry I'm no longer modding for satisfactory, I no longer play and there's a much better modular balancer mod available

**Comment by mikeloeven** [comment]
> 

@RhinoRhys you mentioned there was a nother balancing mod available do you know which one you were referring to?
